import type { Metadata } from "next";
import { Geist, Geist_Mono,Manrope } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import Header from "@/components/custom/header";

const manrope = Manrope({
  subsets: ["latin"],
  variable:"--font-sans"
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
                        'min-h-screen bg-background font-manrope antialiased',
                        manrope.variable
                    )}>
                      <Header/>{/**It is going to display in all the pages */}
       <main> {children}</main>
      </body>
    </html>
  );
}
